<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>
    <xacro:property name="ackerman_offset" value="0.2"/>

    <link name="base_footprint_link">
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
            <material name="blue"/>
        </visual>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link"> 
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2.0} 0.0 0.0"/>
                <material name="red"/>
            </visual>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>
    <xacro:wheel_link prefix="front_right"/>
    <xacro:wheel_link prefix="front_left"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint_link"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-(base_length/4.0)} ${-(base_width + wheel_length)/2.0} 0" rpy="0 0 0"/>
    </joint>
    
    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0.0 1 0.0"/>
        <origin xyz="${-(base_length/4.0)} ${(base_width + wheel_length)/2.0} 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="front_right_wheel_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="-0.575666667" upper="0.575666667" velocity="50.0" effort="1000.0"/>
        <origin xyz="${(base_length/4.0)} ${-(base_width + wheel_length)/2.0} 0" rpy="0 0 0"/>
    </joint>
    
    <joint name="front_left_wheel_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="-0.575666667" upper="0.575666667" velocity="50.0" effort="1000.0"/>
        <origin xyz="${(base_length/4.0)} ${(base_width + wheel_length)/2.0} 0" rpy="0 0 0"/>
    </joint>
    
<!-- 
    <joint name="front_right_wheel__cont_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${(base_length/4.0)} ${-(base_width + wheel_length)/2.0} 0" rpy="0 0 0"/>
    </joint>
    
    <joint name="front_left_wheel_cont_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${(base_length/4.0)} ${(base_width + wheel_length)/2.0} 0.0" rpy="0.0 0.0 0.0"/>
    </joint> -->

</robot>
